name: build
on: push
jobs:
  function:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains('hello','ll')}}
          echo ${{ startsWith('hello','he') }}