name: ENV VARIABLE
on: push
env:
  WF_ENV: "variable d'environnement"

  jobs:
    mon_job-env:
      run-on: ubuntu-latest
      env:
        JOB_ENV: "c'est mon job env"
      steps:
        - name: LOG ENV VARIABLES
          run: |
            echo "JOB_ENV :" $ {{JOB_ENV}}
            echo "WF_ENV :" ${{WF_ENV}}
