name: ENV VARIABLE
on: push
env:
  WF_ENV: "variable d'environnement"
  # secret dans github
  secret_soufiane: ${{ secrets.SECRET_SOUSOU}}

jobs:
  mon_job-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "c'est mon job env"
    steps:
    - name: LOG ENV VARIABLES
      run: |
        echo "JOB_ENV :" ${JOB_ENV}
        echo "WF_ENV :" ${WF_ENV}
